name = "picknwin_rules"
version = "1.0.0"

description = "Pure functional rules engine for PickNWin fantasy sports validation and scoring"
authors = ["PickNWin Team"]
licences = ["Apache-2.0"]
repository = { type = "github", user = "picknwin", repo = "picknwin_rules" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_erlang = ">= 0.25.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"