name: Web CI

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/web/**'
      - 'packages/shared-types/**'
      - '.github/workflows/web-ci.yml'
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/web/**'
      - 'packages/shared-types/**'
      - '.github/workflows/web-ci.yml'

env:
  NODE_VERSION: '20'
  PNPM_VERSION: '8'

jobs:
  lint-and-test:
    name: Lint, Type Check & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/web
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'apps/web/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint:check

      - name: Run type check
        run: npm run typecheck

      - name: Run tests
        run: npm run test

      - name: Build application
        run: npm run build
        env:
          DEPLOY_TARGET: vercel

  build-preview:
    name: Build Preview (GitHub Pages)
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: ./apps/web
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'apps/web/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Build for GitHub Pages
        run: npm run build
        env:
          DEPLOY_TARGET: github-pages
          BASE_PATH: /picknwin

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-build-preview
          path: apps/web/build/
          retention-days: 7