name: Deploy Web to GitHub Pages

on:
  push:
    branches: [main]
    paths:
      - 'apps/web/**'
      - 'packages/shared-types/**'
      - '.github/workflows/web-deploy-pages.yml'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, canceling any in-progress runs to prevent artifact conflicts.
concurrency:
  group: "pages"
  cancel-in-progress: true

env:
  NODE_VERSION: '20'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/web
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: 'apps/web/package-lock.json'

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: sveltekit

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          DEPLOY_TARGET: github-pages
          PUBLIC_API_URL: ${{ vars.PUBLIC_API_URL || 'https://picknwin-api.fly.dev/api' }}
          PUBLIC_WS_URL: ${{ vars.PUBLIC_WS_URL || 'wss://picknwin-api.fly.dev/socket' }}
          PUBLIC_ENV: production

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/build/

  deploy:
    name: Deploy
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4